---
# as root
- hosts: localhost
  become: yes
  tasks:

    - name: glances, htop-like
      apt:
        name: glances
        state: present

    - name: meld, for merging conflicts
      apt:
        name: meld
        state: present

# as user
- hosts: localhost
  tasks:

    - name: Global gitignore file
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitignore_global
        dest: ~/.gitignore_global
        state: link
    - name: Global gitconfig file (includeIf handles work stuff)
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitconfig
        dest: ~/.gitconfig
        state: link
