---
# to apply (alias defined in .bashrc): $ apply-ansible
#
# help for snaps: https://docs.ansible.com/ansible/latest/modules/snap_module.html


# as root
- hosts: localhost
  become: yes
  tasks:

    - name: emacs repo
      apt_repository:
        repo: ppa:kelleyk/emacs
        codename: focal # groovy (20.10) is not yet supported

    - name: emacs
      apt:
        update_cache: yes
        name: emacs27

    - name: spotify
      snap:
        name: spotify

    - name: slack
      snap:
        name: slack
        classic: yes

    - name: cheese (record photo/video with webcam)
      apt:
        name: cheese

    - name: w3m-img (image viewer for w3m, including w3mimgdisplay)
      apt:
        name: w3m-img

    - name: add myself to the video group (for brightnessctl without sudo)
      user:
        name: ch
        groups: video
        append: yes

    - name: i3
      apt:
        name: i3

    - name: espanso (global text expansion)
      apt:
        deb: https://github.com/federico-terzi/espanso/releases/download/v2.2.1/espanso-debian-x11-amd64.deb

    # begin docker
    - name: docker pre-reqs
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu groovy stable

    - name: docker packages
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

    - name: add myself to the docker group
      user:
        name: ch
        groups: docker
        append: yes

    # end docker

    # begin element (matrix chat client)
    - name: element gpg key
      apt_key:
        keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg

    - name: element apt repo
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main

    - name: element (matrix chat client)
      apt:
        update_cache: yes
        pkg:
          - element-desktop
    # end element

    - name: nodejs
      apt:
        name: nodejs

    - name: check mmdc version
      command: mmdc --version
      register: mmdc_version

    - name: mmdc (mermaid cli (drawing diagrams))
      when: mmdc_version.rc != 0
      shell: npm install -g @mermaid-js/mermaid-cli

    - name: java
      apt:
        pkg:
          - openjdk-11-jre # java
          - openjdk-11-jdk-headless # for `jps`

    - name: postgresql-devel (needed for pgcli)
      apt:
        name: libpq-dev

    - name: texlive-latex-recommended (for pandoc pdf generation)
      apt:
        name: texlive-latex-recommended

    - name: cargo (rust package manager)
      apt:
        name: cargo

    - name: zsh
      apt:
        name: zsh

- hosts: localhost
  # requires $ ansible-galaxy install staticdev.signal
  roles:
    - role: staticdev.signal

# as user
- hosts: localhost
  tasks:

    - name: orgparse (parsing org mode in python, used in a i3blocks block for _currently working on_)
      pip:
        name: orgparse
        extra_args: --user

    - name: gh extension list
      command: gh extension list
      register: gh_extension_list

    - name: gh-notify (github cli extension for notifications)
      when: gh_extension_list.stdout.find('meiji163/gh-notify') == -1
      shell: gh extension install meiji163/gh-notify

    - name: Symlink dotfiles/bin to ~/bin
      file:
        src: ~/code/github/chelmertz/dotfiles/bin
        dest: ~/bin
        state: link

    - name: i3blocks, status bar for i3
      file:
        src: ~/dotfiles/.i3blocks.conf
        dest: ~/.i3blocks.conf
        state: link

    - name: Symlink i3 settings
      file:
        src: ~/dotfiles/.i3/config
        dest: ~/.config/i3/config
        state: link

    - name: rofi-blah-blah (snippet manager)
      git:
        repo: https://github.com/chelmertz/rofi-blah-blah
        version: master
        dest: ~/code/github/chelmertz/rofi-blah-blah/

    - name: Clone z (autojump for bash)
      git:
        repo: https://github.com/rupa/z.git
        version: master
        dest: ~/code/github/rupa/z/

    - name: Clone vim-surround (wrap selection in some bracket/tag, and more)
      git:
        repo: https://github.com/tpope/vim-surround.git
        version: master
        dest: ~/.vim/pack/modules/start/vim-surround

    # doom emacs begin
    - name: Clone doom emacs (a nice emacs "distribution"(?))
      git:
        repo: https://github.com/hlissner/doom-emacs.git
        #depth: 1
        dest: ~/.emacs.d
        # now, add ~/.emacs.d/bin to PATH and $ doom install

    - name: Remove default config
      shell: rm -rf ~/.doom.d

    - name: Use my doom emacs config
      file:
        src: ~/dotfiles/.doom.d
        dest: ~/.doom.d
        state: link

    # doom emacs end

    - name: Clone grasp (org capture web pages)
      git:
        repo: https://github.com/karlicoss/grasp
        version: master
        dest: ~/code/github/karlicoss/grasp

    - name: Emoji mode for rofi
      git:
        repo: https://github.com/nkoehring/rofiemoji
        version: master
        dest: ~/code/github/nkoehring/rofiemoji

    - name: treemd (markdown viewer)
      shell: cargo install treemd

    - name: Symlink Xresources
      file:
        src: ~/code/github/chelmertz/dotfiles/.Xresources
        dest: ~/.Xresources
        state: link

    - name: Symlink .ideavimrc
      file:
        src: ~/code/github/chelmertz/dotfiles/.ideavimrc
        dest: ~/.ideavimrc
        state: link

    - name: serve (http server to quickly serve a directory)
      shell: go install github.com/chelmertz/serve@latest

    # start sysz (tui with fuzzy matching for systemd interfaces, systemctl and journalctl)
    - name: "sysz: git"
      git:
        repo: https://github.com/joehillen/sysz.git
        version: master
        dest: ~/code/github/joehillen/sysz

    - name: "sysz: build & install"
      shell: make && install -m755 sysz ~/bin
      args:
        chdir: ~/code/github/joehillen/sysz
    # end sysz

    # fzf-docker
    - name: "fzf-docker: git"
      git:
        repo: https://github.com/chelmertz/fzf-docker.git
        version: master
        dest: ~/code/github/chelmertz/fzf-docker
    # end fzf-docker

