---
# to apply (alias defined in .bashrc): $ apply-ansible
#
# help for snaps: https://docs.ansible.com/ansible/latest/modules/snap_module.html


# as root
- hosts: localhost
  become: yes
  tasks:

    - name: glances, htop-like
      apt:
        name: glances

    - name: meld, for merging conflicts
      apt:
        name: meld

    - name: emacs repo
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: emacs
      apt:
        name: emacs26

    - name: cloc, counts lines of code by language
      apt:
        name: cloc

    - name: simplescreenrecorder
      apt:
        name: simplescreenrecorder

    - name: gron (makes json greppable)
      snap:
        name: gron

    - name: shellcheck
      snap:
        name: shellcheck
        channel: edge

    - name: cheese (record photo/video with webcam)
      apt:
        name: cheese

    - name: copyq (clipboard manager)
      apt:
        name: copyq

    - name: jhead (exif extraction from photos)
      apt:
        name: jhead

    - name: pavucontrol (ubuntu sucks at choosing output device when headset/bluetooth devices are connected, this is the solution)
      apt:
        name: pavucontrol

    - name: yad (dialogs in GTK launched through CLI, like zenity)
      apt:
        name: yad

    - name: bitwarden-cli
      snap:
        name: bw

    - name: keyutils (provides keyctl, needed for bitwarden cli rofi)
      apt:
        name: keyutils

    - name: font awesome
      apt:
        name: fonts-font-awesome

    - name: entr (execute command when files change)
      apt:
        name: entr

    - name: playerctl (media player, lets i3blocks query spotify for current song)
      apt:
        name: playerctl

    - name: jq (parse json, mostly a dep, I use gron more often)
      apt:
        name: jq

    - name: Deps for dunstify, see https://github.com/dunst-project/dunst/wiki/Dependencies
      apt:
        pkg:
          - libdbus-1-dev
          - libx11-dev
          - libxinerama-dev
          - libxrandr-dev
          - libxss-dev
          - libglib2.0-dev
          - libpango1.0-dev
          - libgtk-3-dev
          - libxdg-basedir-dev
          - libnotify-dev

    - name: surfraw (shortcut for searching a bunch of search engines)
      apt:
        name: surfraw

    - name: arandr (gui for xrandr, manage monitors & output)
      apt:
        name: arandr

    - name: autorandr (udev rules + small cli config for detecting monitors being attached/detached)
      apt:
        name: autorandr

    - name: hstr ppa repo
      apt_repository:
        repo: ppa:ultradvorka/ppa

    - name: hstr (history alternative, ctrl+r boosted)
      apt:
        name: hstr

# as user
- hosts: localhost
  tasks:

    - name: Symlink dotfiles, since you modify it so much..
      file:
        src: ~/code/github/chelmertz/dotfiles
        dest: ~/dotfiles
        state: link

    - name: Global gitignore file
      file:
        src: ~/dotfiles/.gitignore_global
        dest: ~/.gitignore_global
        state: link

    - name: Global gitconfig file (includeIf handles work stuff)
      file:
        src: ~/dotfiles/.gitconfig
        dest: ~/.gitconfig
        state: link

    - name: i3blocks, status bar for i3
      file:
        src: ~/dotfiles/.i3blocks.conf
        dest: ~/.i3blocks.conf
        state: link

    - name: Clone z (autojump for bash)
      git:
        repo: https://github.com/rupa/z.git
        version: master
        dest: ~/code/github/rupa/z/

    - name: Clone gallery.sh (script for generating image gallery from folder of image files)
      git:
        repo: https://github.com/Cyclenerd/gallery_shell.git
        version: master
        dest: ~/code/github/Cyclenerd/gallery/

    - name: Add gallery.sh to path
      file:
        src: ~/code/github/Cyclenerd/gallery/gallery.sh
        dest: ~/bin/gallery.sh
        state: link

    - name: Clone dunst (for dunstify)
      git:
        repo: https://github.com/dunst-project/dunst
        version: master
        dest: ~/code/github/dunst-project/dunst

    - name: Build and install dunstify
      shell: make dunstify && cp -f dunstify ~/bin/dunstify
      args:
        chdir: ~/code/github/dunst-project/dunst

#    - name: Emoji mode for rofi
#      git:
#        repo: https://github.com/nkoehring/rofiemoji
#        version: master
#        dest: ~/code/github/nkoehring/rofiemoji

    - name: dust (rust version of du -sh, easier to parse)
      shell: cargo install du-dust

    - name: sd (rust version sed, for the "replace things" use case)
      shell: cargo install sd

    - name: bitwarden-rofi
      git:
        repo: https://github.com/mattydebie/bitwarden-rofi.git
        version: master
        dest: ~/code/github/mattydebie/bitwarden-rofi

    - name: uni (unicode tool for identifying/searching, used in rofi-binding)
      shell: go get arp242.net/uni

    - name: custom search engines for surfraw
      shell: mkdir -p ~/.config/surfraw/ && ln -sf ~/dotfiles/bookmarks ~/.config/surfraw/bookmarks

