---
# as root
- hosts: localhost
  become: yes
  tasks:

    - name: glances, htop-like
      apt:
        name: glances

    - name: meld, for merging conflicts
      apt:
        name: meld

    - name: emacs repo
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: emacs
      apt:
        name: emacs26

# as user
- hosts: localhost
  tasks:

    - name: Global gitignore file
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitignore_global
        dest: ~/.gitignore_global
        state: link
    - name: Global gitconfig file (includeIf handles work stuff)
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitconfig
        dest: ~/.gitconfig
        state: link
