---
# to apply (alias defined in .bashrc): $ apply-ansible
#
# help for snaps: https://docs.ansible.com/ansible/latest/modules/snap_module.html


# as root
- hosts: localhost
  become: yes
  tasks:

    - name: glances, htop-like
      apt:
        name: glances

    - name: meld, for merging conflicts
      apt:
        name: meld

    - name: emacs repo
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: emacs
      apt:
        name: emacs26

    - name: cloc, counts lines of code by language
      apt:
        name: cloc

    - name: simplescreenrecorder
      apt:
        name: simplescreenrecorder

    - name: gron (makes json greppable)
      snap:
        name: gron

    - name: shellcheck
      snap:
        name: shellcheck
        channel: edge

    - name: alacritty (terminal)
      snap:
        name: alacritty
        channel: edge
        classic: yes

    - name: cheese (record photo/video with webcam)
      apt:
        name: cheese

    - name: copyq (clipboard manager)
      apt:
        name: copyq

    - name: jhead (exif extraction from photos)
      apt:
        name: jhead

    - name: espanso (text expander)
      snap:
        name: espanso
        classic: yes

# as user
- hosts: localhost
  tasks:

    - name: Global gitignore file
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitignore_global
        dest: ~/.gitignore_global
        state: link

    - name: Global gitconfig file (includeIf handles work stuff)
      file:
        src: ~/code/github/chelmertz/dotfiles/.gitconfig
        dest: ~/.gitconfig
        state: link

    - name: Clone z (autojump for bash)
      git:
        repo: https://github.com/rupa/z.git
        version: master
        dest: ~/code/github/rupa/z/

    - name: Clone gallery.sh (script for generating image gallery from folder of image files)
      git:
        repo: https://github.com/Cyclenerd/gallery_shell.git
        version: master
        dest: ~/code/github/Cyclenerd/gallery/

    - name: Add gallery.sh to path
      file:
        src: ~/code/github/Cyclenerd/gallery/gallery.sh
        dest: ~/bin/gallery.sh
        state: link

