# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"

  # Do the weird capitalization of MATCHi
  - trigger: ":matchi"
    replace: "MATCHi"

  - trigger: ":shell"
    replace: "```shell\n$|$\n```"

  - trigger: ":pov"
    replace: "point of view"

  - trigger: ":ttm"
    replace: "time to market (TTM)"

  - trigger: ":bc"
    replace: "backwards-compatible"

  - trigger: ":Bc"
    replace: "Backwards-compatible"

  - trigger: ":lgtm"
    replace: "looks good to me"

  - trigger: ":Lgtm"
    replace: "Looks good to me"

  - trigger: ":wdyt"
    replace: "what do you think?"

  - trigger: ":Wdyt"
    replace: "What do you think?"

  - trigger: ":wrt"
    replace: "with regard to"

  - trigger: ":Wrt"
    replace: "With regard to"

  - trigger: ":iirc"
    replace: "if I recall correctly"

  - trigger: ":Iirc"
    replace: "If I recall correctly"

  - trigger: ":afaik"
    replace: "as far as I know"

  - trigger: ":Afaik"
    replace: "As far as I know"

  - trigger: ":AC"
    replace: "acceptance criteria"

  - trigger: ":Ac"
    replace: "Acceptance criteria"

  - trigger: ":afaict"
    replace: "as far as I can tell"

  - trigger: ":Afaict"
    replace: "As far as I can tell"

  - trigger: ":imo"
    replace: "in my opinion"

  - trigger: ":Imo"
    replace: "In my opinion"

  - trigger: ":otoh"
    replace: "on the other hand"

  - trigger: ":Otoh"
    replace: "On the other hand"

# for icons: https://www.compart.com/en/unicode

  - trigger: ":plus"
    replace: "➕"

  - trigger: ":thumb"
    replace: "👍"

  - trigger: ":raised"
    replace: "🙌"

  - trigger: ":pray"
    replace: "🙏"

  - trigger: ":joy"
    replace: "😂"

  - trigger: ":sweat"
    replace: "😅"

  - trigger: ":eye"
    replace: "👀"

  - trigger: ":see"
    replace: "🙈"

  - trigger: ":woozy"
    replace: "🥴"

  - trigger: ":tada"
    replace: "🎉"

  - trigger: "<->"
    replace: "↔"

  - trigger: ":PR"
    replace: "pull request"

  - trigger: ":x"
    replace: "×"

  - trigger: ":mermseq"
    replace: >
      sequenceDiagram

      participant client

      participant api

      client -->>+ api: hello

      api -->>- client: good bye


  # And much more! For more information, visit the docs: https://espanso.org/docs/
